### ISSUE TITLE
GPIO19 does not work

### ISSUE THREAD

**Issue by araobp** [araobp/parking#13]
```
pi@raspberrypi:~/parking/thing $ ./agent.sh
{ MODE: { MODE_0: 0, MODE_1: 1, MODE_2: 2, MODE_3: 3 },
  CS: { none: 64, high: 4, low: 0 },
  ORDER: { msb: false, lsb: true },
  Spi: [Function] }
{ _spi: _spi {}, device: '/dev/spidev0.0' }
thingName: alpr1
{ site_id: '9th floor',
  url: 'http://XXX.XXX.XXX.XXX/',
  upload_address: 'http://localhost:80/push',
  garage_id: '32' }
alprd daemon started.
sensor data reporting started.
connected
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/sys/class/gpio/gpio19/value'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Timeout.loop [as _repeat] (/home/pi/parking/thing/sw.js:59:20)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by araobp** [comment]
fixed by commit 639488108fb4a95cb31b98ce3b110d8f1bd12451
